import { FieldType } from '@prisma/client';
import { SectionTemplate } from './dto/paper-section.dto';

/**
 * PAPER_TEMPLATES — Plantillas de secciones para los 5 papeles de trabajo
 * inteligentes del sistema AuditMind.
 *
 * Claves = paperCode (PT-A1, PT-A2, PT-A4, PT-MEMO, PT-PROG)
 */
export const PAPER_TEMPLATES: Record<string, SectionTemplate[]> = {

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A1: Entendimiento del Negocio
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A1': [
    {
      sectionKey:  'S1',
      label:       'Datos Generales del Cliente',
      description: 'Razón social, RUC/NIT, domicilio fiscal, ejercicio auditado, fecha de cierre.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Incluye razón social, identificación tributaria, domicilio legal y ejercicio auditado.',
    },
    {
      sectionKey:  'S2',
      label:       'Descripción del Negocio',
      description: 'Historia, misión, visión, principales actividades económicas y líneas de negocio.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Describe el modelo de negocio, productos/servicios clave y participación de mercado.',
    },
    {
      sectionKey:  'S3',
      label:       'Entorno Regulatorio',
      description: 'Marcos normativos aplicables: NIIF, NIA, reguladores sectoriales, leyes tributarias.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Lista reguladores, licencias y normas contables que aplican a la entidad.',
    },
    {
      sectionKey:  'S4',
      label:       'Sistemas ERP y TI',
      description: 'ERP principal, módulos implementados, bases de datos, controles de acceso relevantes.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Identifica el ERP, versión, integraciones clave y riesgos de TI relevantes.',
    },
    {
      sectionKey:  'S5',
      label:       'Estructura Organizacional',
      description: 'Organigrama, unidades de negocio clave, gobierno corporativo y comités relevantes.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Describe la estructura jerárquica y los responsables de áreas críticas.',
    },
    {
      sectionKey:  'S6',
      label:       'Cambios Significativos del Período',
      description: 'Adquisiciones, reestructuraciones, cambios de políticas contables, nuevos productos.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Documenta cambios materiales ocurridos en el período bajo revisión.',
    },
    {
      sectionKey:  'S7',
      label:       'Auditorías Anteriores',
      description: 'Hallazgos recurrentes, observaciones relevantes, estado de puntos de mejora.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Resume los principales hallazgos del período anterior y su estado de implementación.',
    },
    {
      sectionKey:  'S8',
      label:       'Factores Externos',
      description: 'Contexto macroeconómico, sectorial, competitivo y regulatorio que afecta a la entidad.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Incluye tendencias de mercado, tasas, tipo de cambio y presiones competitivas relevantes.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A2: Evaluación de Riesgo Inherente
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A2': [
    {
      sectionKey:  'S1',
      label:       'Lista de Áreas / Ciclos Auditados',
      description: 'Identifica todas las áreas, ciclos o procesos que son objeto de la auditoría.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Lista ciclos: Ingresos, Gastos, Nómina, Tesorería, Activos Fijos, etc.',
    },
    {
      sectionKey:  'S2',
      label:       'Saldos Significativos y Afirmaciones',
      description: 'Saldos de estados financieros relevantes y las afirmaciones de auditoría por verificar.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Para cada saldo, indica: cuenta, saldo, moneda y afirmaciones clave (completitud, existencia, valuación).',
    },
    {
      sectionKey:  'S3',
      label:       'Evaluación del Riesgo Inherente (RI)',
      description: 'Factores que aumentan o reducen el RI por área: complejidad, estimaciones, juicio gerencial.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Evalúa cada área con ALTO / MEDIO / BAJO considerando subjetividad, volumen, irregularidades pasadas.',
    },
    {
      sectionKey:  'S4',
      label:       'Score de Riesgo Inherente',
      description: 'Calificación numérica 1-5 o porcentual del RI por área/ciclo.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Asigna score: 1=Muy bajo, 2=Bajo, 3=Medio, 4=Alto, 5=Muy alto. Documenta base de la calificación.',
    },
    {
      sectionKey:  'S5',
      label:       'Riesgos Específicos Identificados',
      description: 'Listado de riesgos concretos por área con probabilidad e impacto estimado.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Para cada riesgo: descripción, área, probabilidad (A/M/B), impacto (A/M/B), respuesta de auditoría.',
    },
    {
      sectionKey:  'S6',
      label:       'Riesgos Significativos NIA 315',
      description: 'Riesgos que requieren procedimientos de auditoría específicos conforme NIA 315.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Identifica riesgos donde el riesgo inherente es alto y los controles pueden ser insuficientes.',
    },
    {
      sectionKey:  'S7',
      label:       'Riesgo de Fraude ACFE',
      description: 'Evaluación del triángulo del fraude: presión, oportunidad y racionalización.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Evalúa indicadores de fraude: incentivos, oportunidades de control débil y cultura organizacional.',
    },
    {
      sectionKey:  'S8',
      label:       'Conclusión de Riesgo Inherente',
      description: 'Nivel general de RI de la auditoría: BAJO / MODERADO / ALTO / MUY ALTO.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['BAJO', 'MODERADO', 'ALTO', 'MUY_ALTO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Emite conclusión general considerando la ponderación de todas las áreas evaluadas.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A4: Cálculo de Materialidad NIA 320
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A4': [
    {
      sectionKey:  'S1',
      label:       'Base de Cálculo',
      description: 'Métrica financiera elegida como base: utilidades antes de impuestos, activos totales, ingresos.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     [
        'UTILIDAD_ANTES_IMPUESTOS',
        'ACTIVOS_TOTALES',
        'INGRESOS_TOTALES',
        'PATRIMONIO_NETO',
        'GASTOS_TOTALES',
        'CAPITAL_TRABAJO',
      ],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Selecciona la base más representativa según NIA 320. Para entidades con fines de lucro, usar utilidad antes de impuestos.',
    },
    {
      sectionKey:  'S2',
      label:       'Porcentaje Aplicado',
      description: 'Porcentaje según guías NIA 320: 5%-10% utilidad, 0.5%-1% activos, 1%-3% ingresos.',
      fieldType:   FieldType.PERCENTAGE,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Documenta el porcentaje y su justificación. Rangos típicos: Utilidad 5-10%, Activos 0.5-1%, Ingresos 1-3%.',
    },
    {
      sectionKey:  'S3',
      label:       'Materialidad Global (MG) — Calculada',
      description: 'Materialidad global = Base × Porcentaje. Campo auto-calculado.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  true,
      isAutoFilled:true,
      sortOrder:   3,
      aiHint:      'MG = S1_valor × S2. Expresar en moneda local. Este campo se auto-calcula.',
    },
    {
      sectionKey:  'S4',
      label:       'Materialidad de Ejecución (ME) — Calculada',
      description: 'ME = 50%-75% de MG para reducir riesgo de que errores no corregidos excedan MG.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  true,
      isAutoFilled:true,
      sortOrder:   4,
      aiHint:      'ME = MG × 0.60 (porcentaje configurable). Se auto-calcula a partir de la MG.',
    },
    {
      sectionKey:  'S5',
      label:       'Umbral de Ajuste Específico (UAE) — Calculado',
      description: 'UAE para errores claramente triviales = 3%-5% de MG.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  false,
      isAutoFilled:true,
      sortOrder:   5,
      aiHint:      'UAE = MG × 0.05. Errores bajo este umbral no se acumulan en la hoja de diferencias.',
    },
    {
      sectionKey:  'S6',
      label:       'Justificación del Criterio Elegido',
      description: 'Razonamiento del auditor para la base y porcentaje seleccionados.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Explica por qué se eligió esa base y ese porcentaje considerando el perfil de la entidad.',
    },
    {
      sectionKey:  'S7',
      label:       'Comparación con Período Anterior',
      description: 'MG del período anterior para evaluar variaciones significativas.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Si la MG varía >20% respecto al período anterior, documenta la causa y considera impacto en alcance.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-MEMO: Memorando de Planificación [MASTER]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-MEMO': [
    {
      sectionKey:   'S1',
      label:        'Encabezado del Memorando',
      description:  'Cliente, período, socio/gerente a cargo, fecha de emisión. Auto-generado.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'audit::header',
      sortOrder:    1,
      aiHint:       'Datos institucionales del encabezado: entidad, año, responsables, normas aplicadas.',
    },
    {
      sectionKey:   'S2',
      label:        'Entendimiento del Negocio (auto desde PT-A1)',
      description:  'Resumen consolidado del PT-A1. Se actualiza automáticamente cuando PT-A1 cambia.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A1::ALL',
      sortOrder:    2,
      aiHint:       'Sintetiza los 8 bloques de PT-A1 en 3-4 párrafos ejecutivos para el memo.',
    },
    {
      sectionKey:   'S3',
      label:        'Evaluación de Riesgo Inherente (auto desde PT-A2)',
      description:  'Resumen de la evaluación de RI y riesgos significativos del PT-A2.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A2::ALL',
      sortOrder:    3,
      aiHint:       'Extrae la conclusión de RI (S8), los riesgos significativos (S6) y el riesgo fraude (S7).',
    },
    {
      sectionKey:   'S4',
      label:        'Materialidad (auto desde PT-A4)',
      description:  'MG, ME y UAE calculados en PT-A4 con su justificación.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A4::ALL',
      sortOrder:    4,
      aiHint:       'Incluye la tabla de materialidad: base, porcentaje, MG, ME, UAE y justificación.',
    },
    {
      sectionKey:  'S5',
      label:       'Enfoque de Auditoría',
      description: 'Estrategia de auditoría: controles vs. sustantivo, áreas de mayor riesgo, enfoque por ciclo.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Define el mix de pruebas de controles vs. procedimientos sustantivos por área de alto riesgo.',
    },
    {
      sectionKey:  'S6',
      label:       'Equipo de Auditoría y Presupuesto de Horas',
      description: 'Integrantes del equipo, roles, horas estimadas por fase y presupuesto total.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Tabla: Nombre | Rol | Fase Planificación | Fase Ejecución | Fase Cierre | Total Horas.',
    },
    {
      sectionKey:  'S7',
      label:       'Cronograma de la Auditoría',
      description: 'Hitos clave: inicio trabajo de campo, entrega de informe borrador, informe final.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Incluye fechas de: reunión de apertura, trabajo de campo, draft a cliente, respuesta, informe final.',
    },
    {
      sectionKey:  'S8',
      label:       'Conclusión — IA + Validación Auditor',
      description: 'Párrafo conclusivo del memorando generado por IA y revisado/firmado por auditor.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'La IA genera el párrafo integrando RI, materialidad y enfoque. El auditor debe revisar y validar.',
    },
    {
      sectionKey:  'S9',
      label:       'Consideraciones Adicionales',
      description: 'Aspectos especiales: going concern, fraude, partes relacionadas, hechos posteriores.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Documenta cualquier aspecto que requiere atención especial durante la ejecución.',
    },
    {
      sectionKey:  'S10',
      label:       'Firmas de Aprobación',
      description: 'Preparado por / Revisado por / Aprobado por con fechas.',
      fieldType:   FieldType.TEXT,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   10,
      aiHint:      'Registro de firmas: Auditor Encargado, Gerente de Auditoría, Socio/CAE con fecha.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-PROG: Programa de Auditoría [MASTER]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-PROG': [
    {
      sectionKey:   'S1',
      label:        'Procedimientos de Auditoría (auto-generados por IA)',
      description:  'Lista de procedimientos generada automáticamente en base al RI y materialidad.',
      fieldType:    FieldType.MATRIX,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A2::S6,PT-A4::S3',
      sortOrder:    1,
      aiHint:       'Genera procedimientos NIA por área de riesgo significativo. Considera nivel RI y enfoque definido.',
    },
    {
      sectionKey:  'S2',
      label:       'Detalle por Procedimiento',
      description: 'Para cada procedimiento: objetivo, alcance, técnica de auditoría, criterio de aceptación.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Columnas: # | Procedimiento | Objetivo | Técnica (inspección/observación/indagación/recálculo) | Criterio.',
    },
    {
      sectionKey:  'S3',
      label:       'Asignación de Responsables',
      description: 'Auditor responsable de ejecutar cada procedimiento.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Asigna cada procedimiento al auditor más adecuado según experiencia y área.',
    },
    {
      sectionKey:  'S4',
      label:       'Horas Estimadas por Procedimiento',
      description: 'Estimación de horas de trabajo de campo por procedimiento.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Total horas debe concordar con presupuesto del PT-MEMO S6.',
    },
    {
      sectionKey:  'S5',
      label:       'Estado de Ejecución',
      description: 'Estado actual de cada procedimiento: Pendiente / En curso / Completado / N/A.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Se actualiza durante la ejecución. Permite seguimiento del avance de la auditoría.',
    },
    {
      sectionKey:  'S6',
      label:       'Vínculo al Papel de Trabajo',
      description: 'Referencia cruzada al papel de trabajo donde se documenta la evidencia.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Formato: índice del papel (ej. B-03, C-01). Permite navegación directa desde el programa.',
    },
    {
      sectionKey:  'S7',
      label:       'Sección Editable — Notas del Auditor',
      description: 'Comentarios, ajustes al alcance o notas del auditor encargado durante la ejecución.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Espacio libre para el auditor: cambios de alcance, incidencias, observaciones de campo.',
    },
    {
      sectionKey:  'S8',
      label:       'Validación de Cobertura',
      description: 'Score de cobertura: % de áreas de riesgo cubiertas por procedimientos programados.',
      fieldType:   FieldType.PERCENTAGE,
      isRequired:  false,
      isAutoFilled:true,
      sourceRef:   'PT-A2::S1,S1',
      sortOrder:   8,
      aiHint:      'Auto-calculado: (áreas con procedimientos asignados / total áreas RI) × 100. Meta ≥ 90%.',
    },
  ],
};
