import { FieldType } from '@prisma/client';
import { SectionTemplate } from './dto/paper-section.dto';

/**
 * PAPER_TEMPLATES — Plantillas de secciones para los 5 papeles de trabajo
 * inteligentes del sistema AuditMind.
 *
 * Claves = paperCode (PT-A1, PT-A2, PT-A4, PT-MEMO, PT-PROG)
 */
export const PAPER_TEMPLATES: Record<string, SectionTemplate[]> = {

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A1: Entendimiento del Negocio
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A1': [
    {
      sectionKey:  'S1',
      label:       'Datos Generales del Cliente',
      description: 'Razón social, RUC/NIT, domicilio fiscal, ejercicio auditado, fecha de cierre.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Incluye razón social, identificación tributaria, domicilio legal y ejercicio auditado.',
    },
    {
      sectionKey:  'S2',
      label:       'Descripción del Negocio',
      description: 'Historia, misión, visión, principales actividades económicas y líneas de negocio.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Describe el modelo de negocio, productos/servicios clave y participación de mercado.',
    },
    {
      sectionKey:  'S3',
      label:       'Entorno Regulatorio',
      description: 'Marcos normativos aplicables: NIIF, NIA, reguladores sectoriales, leyes tributarias.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Lista reguladores, licencias y normas contables que aplican a la entidad.',
    },
    {
      sectionKey:  'S4',
      label:       'Sistemas ERP y TI',
      description: 'ERP principal, módulos implementados, bases de datos, controles de acceso relevantes.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Identifica el ERP, versión, integraciones clave y riesgos de TI relevantes.',
    },
    {
      sectionKey:  'S5',
      label:       'Estructura Organizacional',
      description: 'Organigrama, unidades de negocio clave, gobierno corporativo y comités relevantes.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Describe la estructura jerárquica y los responsables de áreas críticas.',
    },
    {
      sectionKey:  'S6',
      label:       'Cambios Significativos del Período',
      description: 'Adquisiciones, reestructuraciones, cambios de políticas contables, nuevos productos.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Documenta cambios materiales ocurridos en el período bajo revisión.',
    },
    {
      sectionKey:  'S7',
      label:       'Auditorías Anteriores',
      description: 'Hallazgos recurrentes, observaciones relevantes, estado de puntos de mejora.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Resume los principales hallazgos del período anterior y su estado de implementación.',
    },
    {
      sectionKey:  'S8',
      label:       'Factores Externos',
      description: 'Contexto macroeconómico, sectorial, competitivo y regulatorio que afecta a la entidad.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Incluye tendencias de mercado, tasas, tipo de cambio y presiones competitivas relevantes.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A2: Evaluación de Riesgo Inherente
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A2': [
    {
      sectionKey:  'S1',
      label:       'Lista de Áreas / Ciclos Auditados',
      description: 'Identifica todas las áreas, ciclos o procesos que son objeto de la auditoría.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Lista ciclos: Ingresos, Gastos, Nómina, Tesorería, Activos Fijos, etc.',
    },
    {
      sectionKey:  'S2',
      label:       'Saldos Significativos y Afirmaciones',
      description: 'Saldos de estados financieros relevantes y las afirmaciones de auditoría por verificar.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Para cada saldo, indica: cuenta, saldo, moneda y afirmaciones clave (completitud, existencia, valuación).',
    },
    {
      sectionKey:  'S3',
      label:       'Evaluación del Riesgo Inherente (RI)',
      description: 'Factores que aumentan o reducen el RI por área: complejidad, estimaciones, juicio gerencial.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Evalúa cada área con ALTO / MEDIO / BAJO considerando subjetividad, volumen, irregularidades pasadas.',
    },
    {
      sectionKey:  'S4',
      label:       'Score de Riesgo Inherente',
      description: 'Calificación numérica 1-5 o porcentual del RI por área/ciclo.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Asigna score: 1=Muy bajo, 2=Bajo, 3=Medio, 4=Alto, 5=Muy alto. Documenta base de la calificación.',
    },
    {
      sectionKey:  'S5',
      label:       'Riesgos Específicos Identificados',
      description: 'Listado de riesgos concretos por área con probabilidad e impacto estimado.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Para cada riesgo: descripción, área, probabilidad (A/M/B), impacto (A/M/B), respuesta de auditoría.',
    },
    {
      sectionKey:  'S6',
      label:       'Riesgos Significativos NIA 315',
      description: 'Riesgos que requieren procedimientos de auditoría específicos conforme NIA 315.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Identifica riesgos donde el riesgo inherente es alto y los controles pueden ser insuficientes.',
    },
    {
      sectionKey:  'S7',
      label:       'Riesgo de Fraude ACFE',
      description: 'Evaluación del triángulo del fraude: presión, oportunidad y racionalización.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Evalúa indicadores de fraude: incentivos, oportunidades de control débil y cultura organizacional.',
    },
    {
      sectionKey:  'S8',
      label:       'Conclusión de Riesgo Inherente',
      description: 'Nivel general de RI de la auditoría: BAJO / MODERADO / ALTO / MUY ALTO.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['BAJO', 'MODERADO', 'ALTO', 'MUY_ALTO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Emite conclusión general considerando la ponderación de todas las áreas evaluadas.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A4: Cálculo de Materialidad NIA 320
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A4': [
    {
      sectionKey:  'S1',
      label:       'Base de Cálculo',
      description: 'Métrica financiera elegida como base: utilidades antes de impuestos, activos totales, ingresos.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     [
        'UTILIDAD_ANTES_IMPUESTOS',
        'ACTIVOS_TOTALES',
        'INGRESOS_TOTALES',
        'PATRIMONIO_NETO',
        'GASTOS_TOTALES',
        'CAPITAL_TRABAJO',
      ],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Selecciona la base más representativa según NIA 320. Para entidades con fines de lucro, usar utilidad antes de impuestos.',
    },
    {
      sectionKey:  'S2',
      label:       'Porcentaje Aplicado',
      description: 'Porcentaje según guías NIA 320: 5%-10% utilidad, 0.5%-1% activos, 1%-3% ingresos.',
      fieldType:   FieldType.PERCENTAGE,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Documenta el porcentaje y su justificación. Rangos típicos: Utilidad 5-10%, Activos 0.5-1%, Ingresos 1-3%.',
    },
    {
      sectionKey:  'S3',
      label:       'Materialidad Global (MG) — Calculada',
      description: 'Materialidad global = Base × Porcentaje. Campo auto-calculado.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  true,
      isAutoFilled:true,
      sortOrder:   3,
      aiHint:      'MG = S1_valor × S2. Expresar en moneda local. Este campo se auto-calcula.',
    },
    {
      sectionKey:  'S4',
      label:       'Materialidad de Ejecución (ME) — Calculada',
      description: 'ME = 50%-75% de MG para reducir riesgo de que errores no corregidos excedan MG.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  true,
      isAutoFilled:true,
      sortOrder:   4,
      aiHint:      'ME = MG × 0.60 (porcentaje configurable). Se auto-calcula a partir de la MG.',
    },
    {
      sectionKey:  'S5',
      label:       'Umbral de Ajuste Específico (UAE) — Calculado',
      description: 'UAE para errores claramente triviales = 3%-5% de MG.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  false,
      isAutoFilled:true,
      sortOrder:   5,
      aiHint:      'UAE = MG × 0.05. Errores bajo este umbral no se acumulan en la hoja de diferencias.',
    },
    {
      sectionKey:  'S6',
      label:       'Justificación del Criterio Elegido',
      description: 'Razonamiento del auditor para la base y porcentaje seleccionados.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Explica por qué se eligió esa base y ese porcentaje considerando el perfil de la entidad.',
    },
    {
      sectionKey:  'S7',
      label:       'Comparación con Período Anterior',
      description: 'MG del período anterior para evaluar variaciones significativas.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Si la MG varía >20% respecto al período anterior, documenta la causa y considera impacto en alcance.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-MEMO: Memorando de Planificación [MASTER]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-MEMO': [
    {
      sectionKey:   'S1',
      label:        'Encabezado del Memorando',
      description:  'Cliente, período, socio/gerente a cargo, fecha de emisión. Auto-generado.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'audit::header',
      sortOrder:    1,
      aiHint:       'Datos institucionales del encabezado: entidad, año, responsables, normas aplicadas.',
    },
    {
      sectionKey:   'S2',
      label:        'Entendimiento del Negocio (auto desde PT-A1)',
      description:  'Resumen consolidado del PT-A1. Se actualiza automáticamente cuando PT-A1 cambia.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A1::ALL',
      sortOrder:    2,
      aiHint:       'Sintetiza los 8 bloques de PT-A1 en 3-4 párrafos ejecutivos para el memo.',
    },
    {
      sectionKey:   'S3',
      label:        'Evaluación de Riesgo Inherente (auto desde PT-A2)',
      description:  'Resumen de la evaluación de RI y riesgos significativos del PT-A2.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A2::ALL',
      sortOrder:    3,
      aiHint:       'Extrae la conclusión de RI (S8), los riesgos significativos (S6) y el riesgo fraude (S7).',
    },
    {
      sectionKey:   'S4',
      label:        'Materialidad (auto desde PT-A4)',
      description:  'MG, ME y UAE calculados en PT-A4 con su justificación.',
      fieldType:    FieldType.REFERENCE,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A4::ALL',
      sortOrder:    4,
      aiHint:       'Incluye la tabla de materialidad: base, porcentaje, MG, ME, UAE y justificación.',
    },
    {
      sectionKey:  'S5',
      label:       'Enfoque de Auditoría',
      description: 'Estrategia de auditoría: controles vs. sustantivo, áreas de mayor riesgo, enfoque por ciclo.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Define el mix de pruebas de controles vs. procedimientos sustantivos por área de alto riesgo.',
    },
    {
      sectionKey:  'S6',
      label:       'Equipo de Auditoría y Presupuesto de Horas',
      description: 'Integrantes del equipo, roles, horas estimadas por fase y presupuesto total.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Tabla: Nombre | Rol | Fase Planificación | Fase Ejecución | Fase Cierre | Total Horas.',
    },
    {
      sectionKey:  'S7',
      label:       'Cronograma de la Auditoría',
      description: 'Hitos clave: inicio trabajo de campo, entrega de informe borrador, informe final.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Incluye fechas de: reunión de apertura, trabajo de campo, draft a cliente, respuesta, informe final.',
    },
    {
      sectionKey:  'S8',
      label:       'Conclusión — IA + Validación Auditor',
      description: 'Párrafo conclusivo del memorando generado por IA y revisado/firmado por auditor.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'La IA genera el párrafo integrando RI, materialidad y enfoque. El auditor debe revisar y validar.',
    },
    {
      sectionKey:  'S9',
      label:       'Consideraciones Adicionales',
      description: 'Aspectos especiales: going concern, fraude, partes relacionadas, hechos posteriores.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Documenta cualquier aspecto que requiere atención especial durante la ejecución.',
    },
    {
      sectionKey:  'S10',
      label:       'Firmas de Aprobación',
      description: 'Preparado por / Revisado por / Aprobado por con fechas.',
      fieldType:   FieldType.TEXT,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   10,
      aiHint:      'Registro de firmas: Auditor Encargado, Gerente de Auditoría, Socio/CAE con fecha.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-A3: Evaluación de Controles y Riesgo de Control (RC)
  // ──────────────────────────────────────────────────────────────────────────
  'PT-A3': [
    {
      sectionKey:  'S1',
      label:       'Área / Proceso Evaluado',
      description: 'Identifica el área o proceso objeto de la evaluación de controles.',
      fieldType:   FieldType.TEXT,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Ej: Ciclo de Compras, Tesorería, Nómina. Debe coincidir con un área del PT-A2.',
    },
    {
      sectionKey:  'S2',
      label:       'Controles Clave Identificados',
      description: 'Listado de controles preventivos y detectivos relevantes del proceso.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Columnas: # | Descripción del control | Tipo (Preventivo/Detectivo) | Frecuencia | Responsable | Riesgo que mitiga.',
    },
    {
      sectionKey:  'S3',
      label:       'Pruebas de Controles Aplicadas',
      description: 'Procedimientos ejecutados para verificar la efectividad operativa de los controles.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Para cada control: técnica aplicada (inspección, rejecución, observación), tamaño de muestra, período muestreado, resultados obtenidos.',
    },
    {
      sectionKey:  'S4',
      label:       'Excepciones y Desvíos de Control',
      description: 'Controles que fallaron o presentaron desvíos durante las pruebas.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Describe cada excepción: control afectado, naturaleza del desvío, frecuencia de falla, impacto potencial en los estados financieros.',
    },
    {
      sectionKey:  'S5',
      label:       'Evaluación del Riesgo de Control (RC)',
      description: 'Calificación del RC por área una vez evaluados los controles.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['BAJO', 'MODERADO', 'ALTO', 'MUY_ALTO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'BAJO: controles efectivos, pocos desvíos. MODERADO: algunos controles efectivos. ALTO: controles débiles o excepciones frecuentes. MUY_ALTO: sin controles o completamente inefectivos.',
    },
    {
      sectionKey:  'S6',
      label:       'Riesgo de Detección (RD) Resultante',
      description: 'Nivel de RD requerido considerando RI (de PT-A2) y RC evaluado. RD = RA / (RI × RC).',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['BAJO', 'MODERADO', 'ALTO'],
      sourceRef:   'PT-A2::S8',
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Si RI=Alto y RC=Alto → RD debe ser Bajo (más pruebas sustantivas). Si RI=Bajo y RC=Bajo → RD puede ser Alto (menos pruebas sustantivas).',
    },
    {
      sectionKey:  'S7',
      label:       'Impacto en Alcance de Pruebas Sustantivas',
      description: 'Cómo el resultado RC modifica el alcance y naturaleza de las pruebas sustantivas del área.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Describe ajustes al programa de auditoría: qué procedimientos se amplían o reducen, cambios en tamaño de muestra, áreas donde se aplican procedimientos de mayor especificidad.',
    },
    {
      sectionKey:  'S8',
      label:       'Conclusión de Evaluación de Controles',
      description: 'Resumen de la evaluación: nivel de confianza en los controles y enfoque final de auditoría.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Concluye: nivel de confianza depositada en los controles, deficiencias comunicables al management (NIA 265) y estrategia de auditoría resultante.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-COSO: Evaluación COSO 2013 — 5 Componentes / 17 Principios
  // ──────────────────────────────────────────────────────────────────────────
  'PT-COSO': [
    // ── Componente 1 — Entorno de Control (P1-P5) ──
    {
      sectionKey:  'S1',
      label:       'Componente 1 — Entorno de Control (P1-P5)',
      description: '(P1) Integridad y ética · (P2) Independencia del órgano de supervisión · (P3) Estructura y autoridad · (P4) Competencia del personal · (P5) Responsabilidad por el control.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Para cada principio registra: evidencia revisada, fortalezas observadas y debilidades detectadas. Califica cada uno como EFECTIVO, DEBILIDAD SIGNIFICATIVA o DEBILIDAD MATERIAL.',
    },
    {
      sectionKey:  'S1_EVAL',
      label:       'Evaluación — Entorno de Control',
      description: 'Calificación consolidada del Componente 1 considerando los 5 principios.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['EFECTIVO', 'DEBILIDAD_SIGNIFICATIVA', 'DEBILIDAD_MATERIAL'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'EFECTIVO: todos o mayoría de principios satisfactorios. DEBILIDAD_SIGNIFICATIVA: uno o más principios con brechas notables. DEBILIDAD_MATERIAL: deficiencias graves que comprometen la confiabilidad del control.',
    },
    // ── Componente 2 — Evaluación de Riesgos (P6-P9) ──
    {
      sectionKey:  'S2',
      label:       'Componente 2 — Evaluación de Riesgos (P6-P9)',
      description: '(P6) Objetivos específicos definidos · (P7) Identificación y análisis de riesgos · (P8) Riesgo de fraude evaluado · (P9) Cambios significativos identificados.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Vincula P7 con el PT-A2 de riesgos inherentes. Para P8 considera el triángulo ACFE. Para P9 documenta cambios en personal clave, sistemas, regulación o modelo de negocio.',
    },
    {
      sectionKey:  'S2_EVAL',
      label:       'Evaluación — Evaluación de Riesgos',
      description: 'Calificación consolidada del Componente 2.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['EFECTIVO', 'DEBILIDAD_SIGNIFICATIVA', 'DEBILIDAD_MATERIAL'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Si el proceso de evaluación de riesgos es informal o no documenta específicamente el riesgo de fraude, califica como DEBILIDAD_SIGNIFICATIVA.',
    },
    // ── Componente 3 — Actividades de Control (P10-P12) ──
    {
      sectionKey:  'S3',
      label:       'Componente 3 — Actividades de Control (P10-P12)',
      description: '(P10) Selección y desarrollo de controles · (P11) Controles Generales de TI (CGTI) · (P12) Implementación a través de políticas y procedimientos.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Para P11 evalúa: acceso lógico, respaldo de datos, gestión de cambios TI, segregación de funciones en sistemas. Para P12 verifica que los controles estén documentados en manuales vigentes.',
    },
    {
      sectionKey:  'S3_EVAL',
      label:       'Evaluación — Actividades de Control',
      description: 'Calificación consolidada del Componente 3.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['EFECTIVO', 'DEBILIDAD_SIGNIFICATIVA', 'DEBILIDAD_MATERIAL'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Deficiencias en CGTI (accesos no segregados, sin respaldo, gestión de cambios informal) generalmente califican como DEBILIDAD_SIGNIFICATIVA y amplían las pruebas sustantivas.',
    },
    // ── Componente 4 — Información y Comunicación (P13-P15) ──
    {
      sectionKey:  'S4',
      label:       'Componente 4 — Información y Comunicación (P13-P15)',
      description: '(P13) Información relevante y de calidad · (P14) Comunicación interna efectiva · (P15) Comunicación con terceros (reguladores, auditores externos, stakeholders).',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Para P13 evalúa la calidad y oportunidad de la información financiera y operativa. Para P15 incluye canales de denuncia (whistleblowing), comunicación con auditores externos y reguladores.',
    },
    {
      sectionKey:  'S4_EVAL',
      label:       'Evaluación — Información y Comunicación',
      description: 'Calificación consolidada del Componente 4.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['EFECTIVO', 'DEBILIDAD_SIGNIFICATIVA', 'DEBILIDAD_MATERIAL'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Considera si existen sistemas de información confiables, canales formales de comunicación y mecanismos de denuncia activos y efectivos.',
    },
    // ── Componente 5 — Actividades de Monitoreo (P16-P17) ──
    {
      sectionKey:  'S5',
      label:       'Componente 5 — Actividades de Monitoreo (P16-P17)',
      description: '(P16) Evaluaciones continuas e independientes del SCI · (P17) Comunicación oportuna de deficiencias y seguimiento correctivo.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Para P16 considera el rol de auditoría interna, comité de auditoría y autoevaluaciones de control (CRSA). Para P17 verifica que las deficiencias se reporten a la autoridad competente y se corrijan.',
    },
    {
      sectionKey:  'S5_EVAL',
      label:       'Evaluación — Actividades de Monitoreo',
      description: 'Calificación consolidada del Componente 5.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['EFECTIVO', 'DEBILIDAD_SIGNIFICATIVA', 'DEBILIDAD_MATERIAL'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   10,
      aiHint:      'Si no existe función de auditoría interna ni autoevaluaciones formales, califica como DEBILIDAD_SIGNIFICATIVA. Ausencia total de monitoreo = DEBILIDAD_MATERIAL.',
    },
    // ── Evaluación Global ──
    {
      sectionKey:  'S6',
      label:       'Evaluación Global del SCI — COSO 2013',
      description: 'Calificación consolidada del Sistema de Control Interno considerando los 5 componentes y los 17 principios.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['EFECTIVO', 'CON_DEBILIDADES_SIGNIFICATIVAS', 'INEFECTIVO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   11,
      aiHint:      'EFECTIVO: todos los componentes son efectivos y los 17 principios están presentes y funcionando. CON_DEBILIDADES: uno o más componentes presentan debilidades significativas. INEFECTIVO: múltiples debilidades materiales o componentes que no funcionan.',
    },
    {
      sectionKey:  'S7',
      label:       'Implicación en el Enfoque de Auditoría',
      description: 'Estrategia resultante: dependencia de controles vs. enfoque sustantivo expandido.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['ENFOQUE_CONTROLES', 'ENFOQUE_MIXTO', 'ENFOQUE_SUSTANTIVO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   12,
      aiHint:      'ENFOQUE_CONTROLES: SCI efectivo → pruebas de efectividad operativa + pruebas sustantivas reducidas. MIXTO: algunas áreas con controles fuertes, otras débiles. SUSTANTIVO: SCI inefectivo → máximas pruebas de detalle en todas las áreas.',
    },
    {
      sectionKey:  'S8',
      label:       'Deficiencias Comunicables al Management',
      description: 'Deficiencias significativas y materiales que deben ser comunicadas según NIA 265 / NOGAI.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   13,
      aiHint:      'Para cada deficiencia: descripción, componente COSO afectado, clasificación (significativa/material), riesgo resultante, recomendación de corrección. Las materiales van en carta de gerencia obligatoriamente.',
    },
    {
      sectionKey:  'S9',
      label:       'Conclusión del Auditor — SCI',
      description: 'Conclusión narrativa sobre el estado del SCI y su impacto en el plan de auditoría.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   14,
      aiHint:      'Integra: evaluación global COSO, principales fortalezas detectadas, debilidades críticas y cómo estos resultados modifican la naturaleza, alcance y extensión de los procedimientos de auditoría planificados.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-EEFF: Estados Financieros — Cédula Madre [PT INTELIGENTE ESPECIAL]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-EEFF': [
    {
      sectionKey:  'S1',
      label:       'Datos Generales del EEFF',
      description: 'Entidad, período auditado (del/al), moneda funcional, marco de información financiera aplicado.',
      fieldType:   FieldType.TEXT,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Documenta: nombre legal completo, período, moneda (USD/EUR/etc.), marco (NIIF/US GAAP/PCGA locales) y nombre del auditor responsable del papel.',
    },
    {
      sectionKey:  'S2',
      label:       'Balance de Comprobación / Trial Balance',
      description: 'Tabla de cuentas con saldo actual, saldo período anterior, variación y referencia a cédula sumaria correspondiente.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Columnas: Código | Nombre de cuenta | Saldo actual | Saldo anterior | Variación $ | Variación % | Ref. Sumaria (B-01..B-06) | Significativa (✓ si > ME). Importar desde Excel del cliente o digitar manualmente.',
    },
    {
      sectionKey:  'S3',
      label:       'Estado de Situación Financiera (Balance General)',
      description: 'Activos corrientes y no corrientes, pasivos y patrimonio — comparativo dos períodos.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Estructura: Activos Corrientes / Activos No Corrientes / Total Activos / Pasivos Corrientes / Pasivos No Corrientes / Patrimonio / Total Pasivos + Patrimonio. Verificar cuadre: Activos = Pasivos + Patrimonio.',
    },
    {
      sectionKey:  'S4',
      label:       'Estado de Resultados Integral (P&G)',
      description: 'Ingresos, costos, gastos operativos y financieros, utilidad neta — comparativo.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Incluir: Ingresos operacionales / Costo de ventas / Utilidad bruta / Gastos operativos / EBITDA / Depreciación / EBIT / Gastos financieros / UAI / Impuesto corriente / Utilidad neta. Calcular márgenes: bruto, operativo, neto.',
    },
    {
      sectionKey:  'S5',
      label:       'Estado de Flujos de Efectivo',
      description: 'Flujos de actividades operativas, de inversión y de financiamiento.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Método indirecto: Utilidad neta → Ajustes por no monetarios → Capital de trabajo → Flujo operativo → Actividades de inversión → Actividades de financiamiento → Variación neta en caja → Saldo final.',
    },
    {
      sectionKey:  'S6',
      label:       'Verificación de Cuadre del Balance',
      description: 'Confirmación de que Total Activos = Total Pasivos + Patrimonio. Si no cuadra, documenta diferencia.',
      fieldType:   FieldType.BOOLEAN,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'true = balance cuadra correctamente. false = hay diferencia no reconciliada. Si false, solicitar al cliente reconciliación antes de continuar con las pruebas.',
    },
    {
      sectionKey:  'S7',
      label:       'Análisis de Variaciones Significativas (NIA 520)',
      description: 'Cuentas con variación > 20% o monto superior a ME. Expectativa del auditor vs. real.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Para cada variación significativa: cuenta, saldo anterior, saldo actual, variación %, causa probable (explicada por management o proyección), conclusión del auditor (razonable / requiere investigación adicional).',
    },
    {
      sectionKey:  'S8',
      label:       'Estado de Cuentas Auditadas',
      description: 'Seguimiento de qué cuentas tienen trabajo de auditoría completado con referencia al PT de detalle.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Columnas: Cuenta | Ref. PT Detalle (C-01, C-02…) | Auditor responsable | Fecha completado | Estado (Completado / En curso / Pendiente / N/A por inmaterial).',
    },
    {
      sectionKey:  'S9',
      label:       'Conclusión Analítica Preliminar',
      description: 'Evaluación del auditor sobre la razonabilidad general de los EEFF antes de las pruebas de detalle.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Procedimientos analíticos NIA 520: expectativas desarrolladas para cuentas significativas, variaciones explicadas e inexplicadas, áreas de mayor riesgo identificadas desde el análisis horizontal/vertical, conclusión sobre si los EEFF parecen razonables a nivel macro.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-DIFS: Cédula de Diferencias y Ajustes [PT MAESTRO ESPECIAL]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-DIFS': [
    {
      sectionKey:   'S1',
      label:        'Diferencias Identificadas',
      description:  'Tabla maestra de todas las diferencias/errores detectados durante los procedimientos sustantivos.',
      fieldType:    FieldType.MATRIX,
      isRequired:   true,
      isAutoFilled: false,
      sortOrder:    1,
      aiHint:       'Columnas: # | Descripción del error | Cuenta afectada | Ref. PT origen | Tipo (Factual / Por estimación / Proyectado) | Débito | Crédito | Monto neto. Cada excepción documentada en un PT de detalle debe aparecer aquí.',
    },
    {
      sectionKey:   'S2',
      label:        'Acumulado vs. Materialidad — Resumen',
      description:  'Comparación del total acumulado de diferencias contra MG, ME y UAE del proyecto.',
      fieldType:    FieldType.MATRIX,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A4::S3,S4,S5',
      sortOrder:    2,
      aiHint:       'Filas: Diferencias factuales / Por estimación / Proyectadas / Total. Columnas: Acumulado | MG | ME | UAE | ¿Supera ME? | ¿Supera MG? Fuente: materialidad de PT-A4.',
    },
    {
      sectionKey:   'S3',
      label:        'Semáforo de Opinión',
      description:  'Estado automático basado en diferencias acumuladas vs. materialidad global.',
      fieldType:    FieldType.ENUM_SELECT,
      options:      ['VERDE_OPINION_LIMPIA', 'AMARILLO_EVALUAR_IMPACTO', 'ROJO_SALVEDAD_O_ADVERSA'],
      isRequired:   true,
      isAutoFilled: true,
      sortOrder:    3,
      aiHint:       'VERDE: total diferencias < UAE → sin impacto material, opinión limpia posible. AMARILLO: UAE ≤ total < MG → evaluar materialidad e impacto acumulado. ROJO: total ≥ MG → opinión con salvedad o adversa salvo ajuste completo del cliente.',
    },
    {
      sectionKey:   'S4',
      label:        'Propuestas de Ajuste al Cliente',
      description:  'Asientos contables propuestos para corregir cada diferencia significativa.',
      fieldType:    FieldType.MATRIX,
      isRequired:   false,
      isAutoFilled: false,
      sortOrder:    4,
      aiHint:       'Para cada ajuste: # | Descripción | Cuenta Débito | Cuenta Crédito | Monto | Norma aplicable (NIA/NIIF) | Impacto en UAI (↑↓ utilidad en $). Proponer solo ajustes que superen UAE individualmente o en acumulado.',
    },
    {
      sectionKey:   'S5',
      label:        'Respuesta del Cliente a los Ajustes',
      description:  'Registro de la decisión del cliente sobre cada ajuste propuesto.',
      fieldType:    FieldType.MATRIX,
      isRequired:   false,
      isAutoFilled: false,
      sortOrder:    5,
      aiHint:       'Columnas: # Ajuste | Decisión (Acepta / Rechaza / Acepta parcialmente) | Fecha de respuesta | Asiento de ajuste procesado (Sí/No) | Comentario del cliente.',
    },
    {
      sectionKey:   'S6',
      label:        'Total Diferencias No Ajustadas',
      description:  'Suma de diferencias que el cliente no corrigió. Comparación final con MG para determinar impacto en opinión.',
      fieldType:    FieldType.CURRENCY,
      isRequired:   true,
      isAutoFilled: true,
      sortOrder:    6,
      aiHint:       'Total = suma de diferencias rechazadas o parcialmente aceptadas. Si supera MG → modifica la opinión del auditor. Documentar en carta de representación (NIA 580) para que management reconozca las diferencias no ajustadas.',
    },
    {
      sectionKey:   'S7',
      label:        'Recomendación de Tipo de Opinión',
      description:  'Tipo de opinión sugerida conforme NIA 705 basada en diferencias no ajustadas.',
      fieldType:    FieldType.ENUM_SELECT,
      options:      ['OPINION_SIN_MODIFICAR', 'SALVEDAD_POR_IMPORTES_MATERIALES', 'OPINION_ADVERSA', 'ABSTENSION_DE_OPINION'],
      isRequired:   true,
      isAutoFilled: false,
      sortOrder:    7,
      aiHint:       'NIA 705: Sin modificar (EEFF presentan razonablemente en todos los aspectos materiales). Salvedad (efecto material pero no generalizado). Adversa (errores materiales y generalizados). Abstención (limitaciones de alcance tan significativas que no se puede opinar).',
    },
    {
      sectionKey:   'S8',
      label:        'Análisis Narrativo de Ajustes',
      description:  'Resumen ejecutivo del impacto de los ajustes en los EEFF y la opinión del auditor.',
      fieldType:    FieldType.TEXTAREA,
      isRequired:   false,
      isAutoFilled: false,
      sortOrder:    8,
      aiHint:       'El Agente Scriptorium puede generar: "Los ajustes propuestos totalizan $X representando el Y% de la UAI. Los principales ajustes corresponden a [cuentas]. El impacto en el patrimonio es de $Z. Se recomienda..."',
    },
    {
      sectionKey:   'S9',
      label:        'Conclusión Final del Socio / CAE',
      description:  'Decisión definitiva sobre el tipo de opinión y comunicaciones requeridas al management.',
      fieldType:    FieldType.TEXTAREA,
      isRequired:   true,
      isAutoFilled: false,
      sortOrder:    9,
      aiHint:       'Incluye: tipo de opinión definitiva, fundamento (diferencias ajustadas/no ajustadas vs MG), comunicaciones requeridas (carta de gerencia NIA 265, carta de representación NIA 580), fecha de firma del informe y nombre del socio.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-GOV-HAL: Hoja de Hallazgo Gubernamental — 5 elementos NAIG [SMART]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-GOV-HAL': [
    {
      sectionKey:  'S1',
      label:       'Identificación del Hallazgo',
      description: 'Número de hallazgo, área auditada, auditor responsable y fecha de detección.',
      fieldType:   FieldType.TEXT,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Ej: H-001 / Área: UACI / Auditor: [nombre] / Fecha: DD/MM/AAAA.',
    },
    {
      sectionKey:  'S2',
      label:       'Condición — Situación Encontrada',
      description: '¿Qué es lo que se encontró? Describe la situación real observada con evidencia.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Describe objetivamente la situación encontrada con referencia a documentos, montos o datos concretos. Evita juicios de valor.',
    },
    {
      sectionKey:  'S3',
      label:       'Criterio — Marco Normativo Aplicable',
      description: '¿Qué debería ser? Norma, ley, política o procedimiento que debió cumplirse.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Cita artículo específico: Ley AFI, LACAP, NAIG Decreto 7/2016, resoluciones internas, NIIF o mejor práctica aplicable. Incluye número de artículo.',
    },
    {
      sectionKey:  'S4',
      label:       'Causa — Origen de la Condición',
      description: '¿Por qué ocurrió? Razón por la que existe la brecha entre condición y criterio.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Identifica: falta de control, negligencia, falta de capacitación, diseño deficiente del proceso, ausencia de supervisión, recursos insuficientes, etc.',
    },
    {
      sectionKey:  'S5',
      label:       'Efecto — Impacto Real o Potencial',
      description: '¿Qué consecuencias tiene o puede tener? Impacto financiero, legal, operativo o reputacional.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Cuantifica cuando sea posible (montos, % del presupuesto). Menciona riesgos legales, de corrupción, pérdida de fondos públicos o responsabilidad civil.',
    },
    {
      sectionKey:  'S6',
      label:       'Recomendación',
      description: 'Acción correctiva y preventiva sugerida para subsanar la condición.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'La recomendación debe ser específica, medible, alcanzable, dirigida al responsable competente y con plazo definido. Propone mejora del control o del proceso.',
    },
    {
      sectionKey:  'S7',
      label:       'Clasificación del Hallazgo',
      description: 'Severidad conforme NAIG y Manual de Auditoría de la Corte de Cuentas de El Salvador.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['LEVE', 'MODERADO', 'GRAVE', 'MUY_GRAVE'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'LEVE: irregularidad menor sin impacto financiero significativo. MODERADO: incumplimiento con impacto moderado. GRAVE/MUY_GRAVE: posible pérdida de fondos públicos o actos de corrupción.',
    },
    {
      sectionKey:  'S8',
      label:       'Responsable Institucional',
      description: 'Nombre, cargo y unidad organizativa del funcionario que debe atender el hallazgo.',
      fieldType:   FieldType.TEXT,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Debe ser el titular de la unidad auditada o superior jerárquico con competencia para corregir. Incluye nombre completo, cargo y código de unidad.',
    },
    {
      sectionKey:  'S9',
      label:       'Plazo de Atención',
      description: 'Fecha máxima para presentar plan de corrección. Estándar NAIG: 30 días hábiles desde notificación.',
      fieldType:   FieldType.DATE,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Hallazgos muy graves pueden requerir atención inmediata. Cuenta desde la fecha de notificación oficial del informe.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-SEC-RISK: Evaluación de Riesgos ISO 27001:2022 [SMART]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-SEC-RISK': [
    {
      sectionKey:  'S1',
      label:       'Inventario de Activos de Información',
      description: 'Catálogo de activos críticos: sistemas, bases de datos, información sensible, infraestructura.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Columnas: ID | Activo | Tipo (Hardware/Software/Datos/Personas) | Propietario | Clasificación (Pública/Interna/Confidencial/Secreta) | Criticidad (A/M/B).',
    },
    {
      sectionKey:  'S2',
      label:       'Identificación de Amenazas y Vulnerabilidades',
      description: 'Amenazas relevantes y vulnerabilidades técnicas/organizacionales por activo crítico.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Para cada activo: amenaza (ransomware, acceso no autorizado, desastre), vulnerabilidad (parche faltante, control débil, sin política), vector de ataque.',
    },
    {
      sectionKey:  'S3',
      label:       'Evaluación del Riesgo — Probabilidad × Impacto (ISO 27001 cl. 6.1)',
      description: 'Matriz de riesgo de seguridad: probabilidad × impacto en Confidencialidad, Integridad y Disponibilidad.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Escala 1-5. Riesgo = Probabilidad × Impacto. Criterios CVSS para vulnerabilidades técnicas. Priorizar riesgos ≥ 12 (Alto) y ≥ 20 (Crítico).',
    },
    {
      sectionKey:  'S4',
      label:       'Revisión de Controles del Anexo A — ISO 27001:2022',
      description: '93 controles en 4 temas: A.5 Organizacionales, A.6 Personas, A.7 Físicos, A.8 Tecnológicos.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Para cada control aplicable del SoA: estado (Implementado/Parcial/No Implementado), evidencia revisada, observaciones. Focalizar en A.8 tecnológicos: A.8.2 accesos, A.8.16 incidentes, A.8.24 criptografía.',
    },
    {
      sectionKey:  'S5',
      label:       'Plan de Tratamiento de Riesgo',
      description: 'Decisión para cada riesgo identificado: Mitigar / Aceptar / Transferir / Evitar.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Para riesgos altos: propone control específico, responsable y plazo. Para aceptados: justificación firmada por propietario del riesgo y nivel de riesgo residual aceptado.',
    },
    {
      sectionKey:  'S6',
      label:       'Nivel de Madurez del SGSI',
      description: 'Evaluación del nivel de madurez del Sistema de Gestión de Seguridad de la Información.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['INICIAL', 'EN_DESARROLLO', 'DEFINIDO', 'GESTIONADO', 'OPTIMIZADO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'INICIAL=ad-hoc sin procesos formales; EN_DESARROLLO=prácticas básicas; DEFINIDO=documentado y estándar; GESTIONADO=medido y controlado; OPTIMIZADO=mejora continua activa.',
    },
    {
      sectionKey:  'S7',
      label:       'Cumplimiento NRP-23 / NRP-32 (BCR/SSF El Salvador)',
      description: 'Evaluación de cumplimiento de las Normas de Riesgo Operacional y Seguridad Tecnológica del BCR.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Columnas: Artículo | Requisito | Cumple (Sí/No/Parcial) | Evidencia | Observación. NRP-23 para entidades bancarias, NRP-32 para aseguradoras y fondos de pensiones.',
    },
    {
      sectionKey:  'S8',
      label:       'Hallazgos Críticos de Seguridad',
      description: 'Vulnerabilidades o incumplimientos de alto riesgo que requieren atención inmediata.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Listado priorizado: descripción del hallazgo, activo afectado, control fallido, riesgo resultante, recomendación urgente. Hallazgos críticos van al informe ejecutivo.',
    },
    {
      sectionKey:  'S9',
      label:       'Conclusión — Postura de Seguridad',
      description: 'Evaluación ejecutiva del estado de seguridad y principales áreas de mejora.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Sintetiza: nivel de riesgo residual, madurez del SGSI, cumplimiento NRP, principales vulnerabilidades y recomendaciones estratégicas para el CISO y la Dirección.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-BIA: Análisis de Impacto en el Negocio — ISO 22301:2019 [SMART]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-BIA': [
    {
      sectionKey:  'S1',
      label:       'Inventario de Procesos y Funciones Críticas',
      description: 'Identificación de todos los procesos que deben continuar o recuperarse ante una interrupción.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Columnas: Proceso | Área responsable | Criticidad (Alta/Media/Baja) | Recursos clave | Empleados involucrados | ¿Subcontratado?',
    },
    {
      sectionKey:  'S2',
      label:       'RTO — Tiempo Objetivo de Recuperación',
      description: 'Tiempo máximo tolerable de interrupción antes de impacto inaceptable para el negocio.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Columnas: Proceso | RTO definido por negocio (horas) | RTO soportado por TI (horas) | Brecha (Sí/No). Si RTO TI > RTO Negocio = brecha crítica que invalida el plan.',
    },
    {
      sectionKey:  'S3',
      label:       'RPO — Punto Objetivo de Recuperación de Datos',
      description: 'Máxima pérdida de datos tolerable expresada en tiempo desde el último respaldo utilizable.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Columnas: Sistema | RPO requerido | Frecuencia de respaldo actual | ¿Cumple? Validar con ejercicios reales de recuperación de datos.',
    },
    {
      sectionKey:  'S4',
      label:       'MTPoD — Período Máximo de Interrupción Tolerable (ISO 22301)',
      description: 'Tiempo máximo absoluto antes de que la continuidad sea irreversiblemente dañada.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'MTPoD siempre es mayor al RTO. Si el plan no puede recuperar en RTO < MTPoD, el plan es inviable. Incluir impacto regulatorio (suspensión de licencia) y reputacional.',
    },
    {
      sectionKey:  'S5',
      label:       'Dependencias Críticas',
      description: 'Sistemas, personas clave, proveedores y utilidades de los que dependen los procesos críticos.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Para cada proceso: sistemas TI dependientes, proveedor clave (¿tiene BCP propio?), personas críticas y sus suplentes, utilidades (energía, internet, telecomunicaciones).',
    },
    {
      sectionKey:  'S6',
      label:       'Impacto Financiero de la Interrupción',
      description: 'Estimación del costo por hora/día de interrupción por proceso crítico.',
      fieldType:   FieldType.CURRENCY,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Considera: ingresos perdidos, costos de recuperación, penalidades contractuales, multas regulatorias. Útil para justificar inversión en planes de continuidad.',
    },
    {
      sectionKey:  'S7',
      label:       'Revisión de Planes de Continuidad Existentes',
      description: 'Evaluación de BCP/DRP documentados: cobertura, vigencia y pruebas realizadas.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Verifica: ¿Existen planes? ¿Vigentes (< 12 meses)? ¿Cubren procesos críticos? ¿Fueron probados con ejercicio formal? ¿Resultados documentados? ¿Quién activa el plan?',
    },
    {
      sectionKey:  'S8',
      label:       'Brecha vs. Requisitos ISO 22301:2019',
      description: 'Diferencia entre el estado actual del SGCN y los requisitos del estándar internacional.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Cláusulas clave: cl. 8.3 (BIA), cl. 8.4 (estrategias de continuidad), cl. 8.5 (planes), cl. 8.6 (ejercicios y pruebas). Documenta brechas con referencia específica a cláusula.',
    },
    {
      sectionKey:  'S9',
      label:       'Conclusión del BIA — Madurez del SGCN',
      description: 'Evaluación global de la madurez y efectividad del Sistema de Gestión de Continuidad.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['PLANES_ADECUADOS', 'BRECHAS_MENORES', 'BRECHAS_MAYORES', 'SIN_PLAN_CONTINUIDAD'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'PLANES_ADECUADOS: RTO/RPO cubiertos, planes probados, cumple ISO 22301. BRECHAS_MAYORES: RTO no soportado por TI, planes no probados. SIN_PLAN: sin documentación de continuidad.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-AML-RISK: Evaluación de Riesgo LA/FT — NRP-36 / GAFI [SMART]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-AML-RISK': [
    {
      sectionKey:  'S1',
      label:       'Evaluación de Riesgo por Tipo de Cliente',
      description: 'Segmentación de clientes por nivel de riesgo LA/FT según NRP-36 y GAFI Recomendación 1.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   1,
      aiHint:      'Columnas: Segmento | % portafolio | Indicadores de riesgo (PEP, jurisdicción, industria) | Nivel riesgo (Bajo/Medio/Alto/Muy Alto) | DDC requerida (simplificada/estándar/reforzada).',
    },
    {
      sectionKey:  'S2',
      label:       'Evaluación de Riesgo por Productos y Servicios',
      description: 'Análisis del riesgo inherente LA/FT de cada producto o servicio ofrecido.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Para cada producto: transferencias internacionales, efectivo, corresponsalía, criptoactivos/Chivo. Evalúa: anonimato, velocidad, facilidad para estructurar operaciones.',
    },
    {
      sectionKey:  'S3',
      label:       'Evaluación de Riesgo por Canales de Distribución',
      description: 'Canales que facilitan o dificultan la identificación del cliente y monitoreo de operaciones.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Evalúa: sucursales presenciales, banca digital/app, cajeros, corresponsales no bancarios, API/Fintech. Riesgo mayor en canales sin contacto visual o verificación biométrica.',
    },
    {
      sectionKey:  'S4',
      label:       'Evaluación de Riesgo por Zonas Geográficas',
      description: 'Riesgo geográfico según listas GAFI, países no cooperantes y zonas de alto riesgo local.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Referencias: Lista GAFI de jurisdicciones no cooperantes, Índice de Basilea AML, EFCC. Para El Salvador: municipios con alta actividad criminal. Incluye exposición a jurisdicciones offshore.',
    },
    {
      sectionKey:  'S5',
      label:       'Matriz de Riesgo Inherente LA/FT Consolidada',
      description: 'Ponderación de las 4 categorías de riesgo para determinar el riesgo inherente total.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Ponderación NRP-36: Clientes 40% / Productos 30% / Canales 20% / Geografía 10%. Score total = suma ponderada. Escala 1-4 donde 4 = Muy Alto.',
    },
    {
      sectionKey:  'S6',
      label:       'Nivel de Riesgo Inherente LA/FT',
      description: 'Clasificación final del riesgo inherente del sujeto obligado ante LA/FT.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['BAJO', 'MEDIO', 'ALTO', 'MUY_ALTO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Si el riesgo es Alto o Muy Alto: programa PLD debe ser robusto, Oficial de Cumplimiento con más recursos, DDC reforzada obligatoria para clientes de riesgo alto.',
    },
    {
      sectionKey:  'S7',
      label:       'Evaluación de Controles PLD — 3 Líneas de Defensa',
      description: 'Efectividad del programa PLD en sus 3 líneas: operación, cumplimiento/riesgo, auditoría.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Línea 1 (negocio): identifica y reporta. Línea 2 (Oficial Cumplimiento): políticas, monitoreo, capacitación. Línea 3 (AI/AE): revisión independiente. Para cada línea: fortalezas, debilidades, calificación.',
    },
    {
      sectionKey:  'S8',
      label:       'Nivel de Riesgo Residual LA/FT',
      description: 'Riesgo residual después de considerar la efectividad de los controles del programa PLD.',
      fieldType:   FieldType.ENUM_SELECT,
      options:     ['BAJO', 'MEDIO', 'ALTO', 'MUY_ALTO'],
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   8,
      aiHint:      'Si controles efectivos: riesgo residual < inherente. Si débiles: riesgo residual ≈ inherente. Riesgo residual Alto/Muy Alto = acción correctiva urgente para Comité de Cumplimiento.',
    },
    {
      sectionKey:  'S9',
      label:       'Conclusión — Efectividad del Programa PLD/ALD',
      description: 'Evaluación ejecutiva de la efectividad del programa de prevención de lavado de dinero.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   9,
      aiHint:      'Sintetiza: riesgo inherente, efectividad de controles, riesgo residual, cumplimiento NRP-36/LCDA/Instructivo UIF V3, hallazgos críticos y recomendaciones para el Comité de Cumplimiento.',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // PT-PROG: Programa de Auditoría [MASTER]
  // ──────────────────────────────────────────────────────────────────────────
  'PT-PROG': [
    {
      sectionKey:   'S1',
      label:        'Procedimientos de Auditoría (auto-generados por IA)',
      description:  'Lista de procedimientos generada automáticamente en base al RI y materialidad.',
      fieldType:    FieldType.MATRIX,
      isRequired:   true,
      isAutoFilled: true,
      sourceRef:    'PT-A2::S6,PT-A4::S3',
      sortOrder:    1,
      aiHint:       'Genera procedimientos NIA por área de riesgo significativo. Considera nivel RI y enfoque definido.',
    },
    {
      sectionKey:  'S2',
      label:       'Detalle por Procedimiento',
      description: 'Para cada procedimiento: objetivo, alcance, técnica de auditoría, criterio de aceptación.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   2,
      aiHint:      'Columnas: # | Procedimiento | Objetivo | Técnica (inspección/observación/indagación/recálculo) | Criterio.',
    },
    {
      sectionKey:  'S3',
      label:       'Asignación de Responsables',
      description: 'Auditor responsable de ejecutar cada procedimiento.',
      fieldType:   FieldType.MATRIX,
      isRequired:  true,
      isAutoFilled:false,
      sortOrder:   3,
      aiHint:      'Asigna cada procedimiento al auditor más adecuado según experiencia y área.',
    },
    {
      sectionKey:  'S4',
      label:       'Horas Estimadas por Procedimiento',
      description: 'Estimación de horas de trabajo de campo por procedimiento.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   4,
      aiHint:      'Total horas debe concordar con presupuesto del PT-MEMO S6.',
    },
    {
      sectionKey:  'S5',
      label:       'Estado de Ejecución',
      description: 'Estado actual de cada procedimiento: Pendiente / En curso / Completado / N/A.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   5,
      aiHint:      'Se actualiza durante la ejecución. Permite seguimiento del avance de la auditoría.',
    },
    {
      sectionKey:  'S6',
      label:       'Vínculo al Papel de Trabajo',
      description: 'Referencia cruzada al papel de trabajo donde se documenta la evidencia.',
      fieldType:   FieldType.MATRIX,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   6,
      aiHint:      'Formato: índice del papel (ej. B-03, C-01). Permite navegación directa desde el programa.',
    },
    {
      sectionKey:  'S7',
      label:       'Sección Editable — Notas del Auditor',
      description: 'Comentarios, ajustes al alcance o notas del auditor encargado durante la ejecución.',
      fieldType:   FieldType.TEXTAREA,
      isRequired:  false,
      isAutoFilled:false,
      sortOrder:   7,
      aiHint:      'Espacio libre para el auditor: cambios de alcance, incidencias, observaciones de campo.',
    },
    {
      sectionKey:  'S8',
      label:       'Validación de Cobertura',
      description: 'Score de cobertura: % de áreas de riesgo cubiertas por procedimientos programados.',
      fieldType:   FieldType.PERCENTAGE,
      isRequired:  false,
      isAutoFilled:true,
      sourceRef:   'PT-A2::S1,S1',
      sortOrder:   8,
      aiHint:      'Auto-calculado: (áreas con procedimientos asignados / total áreas RI) × 100. Meta ≥ 90%.',
    },
  ],

  // ══════════════════════════════════════════════════════════════════════════
  //  PLANTILLAS FISCALES — Auditoría Fiscal El Salvador v6.1 (NACOT 2018)
  //  La NACOT 2018 es la NORMA TÉCNICA RECTORA del encargo fiscal salvadoreño.
  // ══════════════════════════════════════════════════════════════════════════

  // PT-FISC-INDEP: Evaluación de Independencia — NACOT Sección 2 / CIEPC 2018 [SMART]
  'PT-FISC-INDEP': [
    {
      sectionKey: 'S1', label: 'Tipo de Amenaza a Evaluar (CIEPC + NACOT Sec. 2)',
      description: 'Interés propio, autorevisión, abogacía, familiaridad e intimidación frente al contribuyente.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Columnas: Amenaza | ¿Existe? (Sí/No) | Descripción del hecho observado | Nivel (Alto/Medio/Bajo). Evalúa las 5 amenazas del CIEPC.',
    },
    {
      sectionKey: 'S2', label: 'Servicios Prohibidos para el Mismo Cliente',
      description: 'Preparación de declaraciones que luego se dictaminan, representación ante DGII, registro contable.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 2,
      aiHint: 'Identifica si la firma prestó al mismo cliente servicios incompatibles con dictaminar (autorevisión/abogacía).',
    },
    {
      sectionKey: 'S3', label: 'Evaluación de Honorarios',
      description: 'Si los honorarios del cliente superan el 15% de los ingresos de la firma → amenaza de interés propio.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Indica honorarios del encargo, % sobre ingresos totales de la firma y si supera el umbral del 15%.',
    },
    {
      sectionKey: 'S4', label: 'Salvaguardas Aplicadas',
      description: 'Medidas para eliminar o reducir las amenazas a un nivel aceptable según el CIEPC 2018.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Para cada amenaza identificada, documenta la salvaguarda concreta aplicada.',
    },
    {
      sectionKey: 'S5', label: 'Conclusión sobre el Encargo',
      description: 'El encargo puede aceptarse / debe rechazarse / continúa con salvaguardas.',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 5,
      options: ['Aceptable', 'Aceptable con salvaguardas', 'Debe rechazarse'],
      aiHint: 'Concluye con base en las amenazas y salvaguardas evaluadas.',
    },
    {
      sectionKey: 'S6', label: 'Declaración de Independencia del Equipo',
      description: 'Firma de cada miembro del equipo auditor declarando independencia respecto del contribuyente.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 6,
      aiHint: 'Lista cada miembro del equipo con su declaración de independencia para firma digital.',
    },
  ],

  // PT-FISC-QC: Control de Calidad del Encargo — NACOT Sección 3 [SMART]
  'PT-FISC-QC': [
    {
      sectionKey: 'S1', label: 'Aplicabilidad de la Revisión de Calidad',
      description: 'Grandes Contribuyentes, ingresos > $5,000,000, riesgo de fraude o incumplimientos previos significativos.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Determina si el encargo requiere revisión de calidad según los criterios de alto riesgo de la NACOT Sec. 3.',
    },
    {
      sectionKey: 'S2', label: 'Revisor de Calidad Designado',
      description: 'Persona que NO participó en el encargo — nombre, cargo y fecha de designación.',
      fieldType: FieldType.TEXT, isRequired: true, isAutoFilled: false, sortOrder: 2,
      aiHint: 'Nombre, cargo y carné CVPCPA del revisor independiente del encargo.',
    },
    {
      sectionKey: 'S3', label: 'Áreas de Revisión de Calidad',
      description: 'Competencias del equipo, evaluación de riesgos, suficiencia de evidencia, clasificación de hallazgos, estructura del dictamen.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Columnas: Área de revisión | ¿Conforme? (Sí/No) | Observación. Cubre las 6 áreas críticas de la NACOT.',
    },
    {
      sectionKey: 'S4', label: 'Puntos Observados por el Revisor',
      description: 'Aspectos que el revisor identificó para corrección antes de la firma del dictamen.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Lista los puntos observados que deben corregirse antes de emitir el dictamen.',
    },
    {
      sectionKey: 'S5', label: 'Respuesta del Equipo del Encargo',
      description: 'Correcciones realizadas a los puntos observados por el revisor de calidad.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 5,
      aiHint: 'Documenta cómo el equipo resolvió cada punto observado.',
    },
    {
      sectionKey: 'S6', label: 'Aprobación del Dictamen',
      description: 'El revisor de calidad autoriza (o no) la firma del dictamen fiscal.',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 6,
      options: ['Aprobado para firma', 'Pendiente de correcciones', 'No aprobado'],
      aiHint: 'El dictamen (AF-D5) no puede firmarse hasta que esta sección esté Aprobada.',
    },
  ],

  // PT-FISC-ENCARGO: Carta de Encargo Fiscal — Términos NACOT Sección 4 [SMART]
  'PT-FISC-ENCARGO': [
    {
      sectionKey: 'S1', label: 'Identificación de las Partes',
      description: 'Contribuyente (nombre, NIT, NRC) y firma auditora (razón social, carné CVPCPA del socio).',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Datos completos del contribuyente y de la firma auditora firmante.',
    },
    {
      sectionKey: 'S2', label: 'Naturaleza del Encargo',
      description: 'Aseguramiento sobre el cumplimiento de obligaciones tributarias según la NACOT 2018.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 2,
      aiHint: 'Describe el encargo de aseguramiento sobre cumplimiento tributario bajo la NACOT.',
    },
    {
      sectionKey: 'S3', label: 'Período Cubierto',
      description: 'Ejercicio fiscal del 01/01/XXXX al 31/12/XXXX.',
      fieldType: FieldType.TEXT, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Período fiscal exacto cubierto por el dictamen.',
    },
    {
      sectionKey: 'S4', label: 'Criterios de Evaluación',
      description: 'Código Tributario, LISR, Ley IVA y demás leyes tributarias vigentes en el período.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Marco legal tributario que sirve de criterio para el examen.',
    },
    {
      sectionKey: 'S5', label: 'Responsabilidades de la Firma',
      description: 'Realizar el encargo según la NACOT, NIA supletoriamente y el CIEPC.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 5,
      aiHint: 'Responsabilidades de la firma auditora conforme a la NACOT Sec. 4.',
    },
    {
      sectionKey: 'S6', label: 'Responsabilidades del Contribuyente',
      description: 'Acceso irrestricto a la información, carga en el SDF antes del 30 de abril, veracidad, rectificación.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 6,
      aiHint: 'Obligaciones del contribuyente, incluida la carga oportuna de EF y anexos en el SDF.',
    },
    {
      sectionKey: 'S7', label: 'Honorarios y Forma de Pago',
      description: 'Honorarios pactados por el encargo y condiciones de pago.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 7,
      aiHint: 'Monto de honorarios y forma de pago.',
    },
    {
      sectionKey: 'S8', label: 'Plazo de Entrega',
      description: 'El Dictamen e Informe Fiscal se presenta en el SDF a más tardar el 31 de mayo.',
      fieldType: FieldType.TEXT, isRequired: true, isAutoFilled: false, sortOrder: 8,
      aiHint: 'Fecha límite de presentación en el SDF (31 de mayo).',
    },
    {
      sectionKey: 'S9', label: 'Limitaciones al Alcance',
      description: 'Si el contribuyente restringe el acceso a información, se comunicará en el dictamen.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 9,
      aiHint: 'Documenta posibles limitaciones al alcance y su tratamiento en el dictamen.',
    },
    {
      sectionKey: 'S10', label: 'Firmas',
      description: 'Representante legal del contribuyente + socio firmante de la firma auditora.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 10,
      aiHint: 'Bloque de firmas de ambas partes.',
    },
  ],

  // PT-FISC-RISK: Riesgo de Incumplimiento Fiscal — NIA 315 + NACOT Sección 5 [SMART]
  'PT-FISC-RISK': [
    {
      sectionKey: 'S1', label: 'Riesgo Inherente de Incumplimiento por Impuesto',
      description: 'Factores específicos por impuesto: ISR, IVA, Retenciones ISR y Obligaciones Formales (DTE).',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Columnas: Impuesto | Factores de riesgo inherente | Nivel (Alto/Medio/Bajo). Cubre ISR, IVA, Retenciones y Obligaciones Formales.',
    },
    {
      sectionKey: 'S2', label: 'Riesgo de Control Tributario',
      description: 'Evaluación del SCI sobre los procesos fiscales (proviene de A-02 / SCI Tributario).',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: true, sourceRef: 'A-02::S7', sortOrder: 2,
      aiHint: 'Sintetiza la evaluación del control interno tributario y su efecto en el riesgo.',
    },
    {
      sectionKey: 'S3', label: 'Riesgo de Incumplimiento Significativo (NACOT)',
      description: 'Áreas donde el incumplimiento sería material conforme a la NACOT Sección 5.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Identifica las áreas de incumplimiento significativo según la materialidad fiscal.',
    },
    {
      sectionKey: 'S4', label: 'Historial de Incumplimientos',
      description: 'Fiscalizaciones anteriores de la DGII, requerimientos recibidos y multas pagadas.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Resume el historial de fiscalizaciones, requerimientos y sanciones del contribuyente.',
    },
    {
      sectionKey: 'S5', label: 'Factores Externos',
      description: 'Cambios normativos en el período que el contribuyente debía implementar.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 5,
      aiHint: 'Cambios legales/reglamentarios del período relevantes para el cumplimiento.',
    },
    {
      sectionKey: 'S6', label: 'Riesgo de Fraude Fiscal (NIA 240 adaptada)',
      description: 'Indicadores de evasión intencional vs. error involuntario.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 6,
      aiHint: 'Evalúa indicadores de fraude/evasión intencional; si son altos, activa procedimientos forenses.',
    },
    {
      sectionKey: 'S7', label: 'Score de Riesgo por Impuesto',
      description: 'Alto / Medio / Bajo por impuesto — determina la intensidad de los procedimientos.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 7,
      aiHint: 'Columnas: Impuesto | Score (Alto/Medio/Bajo) | Justificación. Alimenta la intensidad del Programa Fiscal.',
    },
    {
      sectionKey: 'S8', label: 'Respuesta Planeada',
      description: 'Procedimientos específicos por área de riesgo Alto — alimenta el Programa de Auditoría Fiscal.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 8,
      aiHint: 'Define la respuesta de auditoría por cada área de riesgo Alto identificada.',
    },
  ],

  // PT-FISC-AML: Indicadores de Lavado de Activos — LCLDA / Reforma 2024 / FATF [SMART]
  'PT-FISC-AML': [
    {
      sectionKey: 'S1', label: 'Identificación del Contribuyente como Sujeto Obligado',
      description: '¿El contribuyente es sujeto obligado de reporte bajo la LCLDA?',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Determina si el contribuyente es sujeto obligado bajo la LCLDA reformada 2024.',
    },
    {
      sectionKey: 'S2', label: 'Indicadores de Lavado en Operaciones',
      description: 'Efectivo significativo sin justificación, contrapartes de alto riesgo (FATF), smurfing, ingresos inconsistentes, listas de sanciones.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 2,
      aiHint: 'Columnas: Indicador | ¿Detectado? (Sí/No) | Operación/Evidencia | Riesgo. Aplica las 40 recomendaciones FATF/GAFI.',
    },
    {
      sectionKey: 'S3', label: 'Operaciones con Paraísos Fiscales',
      description: 'Transacciones con jurisdicciones de baja tributación — se vinculan al PT de Precios de Transferencia.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Lista operaciones con paraísos fiscales; activa el análisis de Precios de Transferencia (AF-07).',
    },
    {
      sectionKey: 'S4', label: 'Verificación del Programa AML del Contribuyente',
      description: 'Oficial de Cumplimiento registrado en la UIF, ROS presentados, políticas KYC documentadas.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Si es sujeto obligado, verifica Oficial de Cumplimiento, ROS y políticas KYC.',
    },
    {
      sectionKey: 'S5', label: 'Obligaciones del Auditor Fiscal bajo la LCLDA',
      description: 'Reportar a la UIF ante indicadores claros de lavado; prohibición de tipping-off (no alertar al cliente).',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 5,
      aiHint: 'Documenta las obligaciones de reporte del auditor y el cumplimiento de la prohibición de tipping-off.',
    },
    {
      sectionKey: 'S6', label: 'Nivel de Riesgo AML',
      description: 'Bajo / Medio / Alto — si es Alto, documenta indicadores y acciones tomadas.',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 6,
      options: ['Bajo', 'Medio', 'Alto'],
      aiHint: 'Concluye el nivel de riesgo AML del contribuyente.',
    },
  ],

  // PT-FISC-PT: Precios de Transferencia — Art. 199-A CT / OCDE / BEPS [SMART]
  'PT-FISC-PT': [
    {
      sectionKey: 'S1', label: 'Identificación de Partes Relacionadas (Art. 199-A/B CT)',
      description: 'Participación ≥ 25%, subsidiarias/matrices/hermanas, paraísos fiscales, posición gerencial clave.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Columnas: Parte relacionada | Tipo de relación | País | ¿Paraíso fiscal?. Aplica los criterios del Art. 199-A/B CT.',
    },
    {
      sectionKey: 'S2', label: 'Inventario de Operaciones Intercompany',
      description: 'Todas las transacciones con partes relacionadas: bienes, servicios, préstamos, intangibles, garantías.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 2,
      aiHint: 'Columnas: Operación | Tipo | Monto | Parte relacionada. Inventario completo del período.',
    },
    {
      sectionKey: 'S3', label: 'Verificación del Estudio de Precios de Transferencia',
      description: 'Existencia del estudio, preparación por especialista, método apropiado y rango arm\'s length actualizado.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Evalúa existencia, calidad y vigencia del estudio de precios de transferencia.',
    },
    {
      sectionKey: 'S4', label: 'Los 5 Métodos OCDE — Método Aplicado',
      description: 'CUP, Precio de Reventa (RPM), Costo Adicionado (CPM), Margen Neto (TNMM), Distribución de Utilidades (PS).',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 4,
      options: ['CUP (Precio Comparable No Controlado)', 'RPM (Precio de Reventa)', 'CPM (Costo Adicionado)', 'TNMM (Margen Neto)', 'PS (Distribución de Utilidades)'],
      aiHint: 'Verifica que el método seleccionado sea el más apropiado según las Directrices OCDE 2022.',
    },
    {
      sectionKey: 'S5', label: 'Análisis de Comparabilidad',
      description: 'Empresas o transacciones comparables usadas en el estudio.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 5,
      aiHint: 'Resume los comparables seleccionados y su pertinencia.',
    },
    {
      sectionKey: 'S6', label: 'Ajustes de Comparabilidad',
      description: 'Ajustes por diferencias en funciones, activos y riesgos (análisis FAR).',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 6,
      aiHint: 'Documenta los ajustes de comparabilidad aplicados.',
    },
    {
      sectionKey: 'S7', label: 'Conclusión — Principio de Plena Competencia',
      description: '¿Las operaciones intercompany cumplen el principio de plena competencia (arm\'s length)?',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 7,
      options: ['Cumple plena competencia', 'No cumple — requiere ajuste'],
      aiHint: 'Concluye si los precios pactados están dentro del rango de plena competencia.',
    },
    {
      sectionKey: 'S8', label: 'Cuantificación del Ajuste al ISR',
      description: 'Si los precios no son de mercado → ajuste al ISR (Art. 199-C: tasa especial 25% para paraísos).',
      fieldType: FieldType.CURRENCY, isRequired: false, isAutoFilled: false, sortOrder: 8,
      aiHint: 'Monto del ajuste al ISR por operaciones fuera de mercado. Alimenta la conciliación fiscal y la cédula de diferencias.',
    },
    {
      sectionKey: 'S9', label: 'Informe F982 — Presentación Oportuna',
      description: 'Verificación de la presentación oportuna del Informe de Operaciones con Sujetos Relacionados.',
      fieldType: FieldType.BOOLEAN, isRequired: true, isAutoFilled: false, sortOrder: 9,
      aiHint: 'Indica si el F982 fue presentado oportunamente ante la DGII.',
    },
  ],

  // PT-FISC-ZF: Dictamen Semestral — Zona Franca / Servicios Internacionales [SMART]
  'PT-FISC-ZF': [
    {
      sectionKey: 'S1', label: 'Aplicabilidad del Régimen',
      description: '¿El contribuyente opera bajo régimen de Zona Franca / Parque de Servicios Internacionales?',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Determina si aplica el dictamen semestral especial del régimen.',
    },
    {
      sectionKey: 'S2', label: 'Período del Dictamen Semestral',
      description: '1er semestre (ene-jun) → SDF antes del 31 ago; 2do semestre (jul-dic) → antes del 28 feb siguiente.',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 2,
      options: ['1er semestre (ene-jun)', '2do semestre (jul-dic)'],
      aiHint: 'Selecciona el semestre dictaminado y su fecha límite de presentación en el SDF.',
    },
    {
      sectionKey: 'S3', label: 'Verificación de Requisitos para Mantener el Régimen',
      description: 'Mínimo de empleados, actividades autorizadas (MEPYD), % de exportaciones, reportes al MEPYD y DGII.',
      fieldType: FieldType.MATRIX, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Columnas: Requisito | ¿Cumple? (Sí/No) | Evidencia. Verifica las condiciones de permanencia del régimen.',
    },
    {
      sectionKey: 'S4', label: 'Análisis Fiscal del Régimen de Exención',
      description: 'Operaciones exentas autorizadas, límite de mercado local, IVA tasa cero en exportaciones y devoluciones.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Verifica que las operaciones exentas correspondan a lo autorizado y el tratamiento del mercado local.',
    },
    {
      sectionKey: 'S5', label: 'Cumplimiento de Obligaciones Formales del Régimen',
      description: 'Reportes mensuales de divisas al BCR, informes trimestrales al MEPYD, declaraciones de importación de insumos.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 5,
      aiHint: 'Verifica los reportes especiales al BCR, MEPYD y DGA exigidos por el régimen.',
    },
    {
      sectionKey: 'S6', label: 'Dictamen Semestral',
      description: 'Estructura del dictamen usando el modelo del SDF para semestrales.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 6,
      aiHint: 'Redacta el dictamen semestral conforme al modelo SDF. Integra resultados al dictamen anual (AF-D5).',
    },
  ],

  // PT-FISC-DICT: Dictamen Fiscal — Modelo Oficial NACOT Anexo 1 [MASTER]
  'PT-FISC-DICT': [
    {
      sectionKey: 'S1', label: 'Título',
      description: '"Dictamen Fiscal" — obligatorio según la NACOT.',
      fieldType: FieldType.TEXT, isRequired: true, isAutoFilled: false, sortOrder: 1,
      aiHint: 'Título exacto: "Dictamen Fiscal".',
    },
    {
      sectionKey: 'S2', label: 'Destinatario',
      description: '"A los accionistas (o propietario) de [nombre del contribuyente]".',
      fieldType: FieldType.TEXT, isRequired: true, isAutoFilled: false, sortOrder: 2,
      aiHint: 'Destinatario conforme al modelo del Anexo 1 de la NACOT.',
    },
    {
      sectionKey: 'S3', label: 'Párrafo Introductorio',
      description: 'Examen del cumplimiento de obligaciones tributarias del ejercicio del 01/01 al 31/12 de 20XX.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 3,
      aiHint: 'Redacta el párrafo introductorio según el modelo NACOT Anexo 1.',
    },
    {
      sectionKey: 'S4', label: 'Responsabilidad de la Administración',
      description: 'El contribuyente es responsable del cumplimiento y del mantenimiento de los registros que lo sustentan.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 4,
      aiHint: 'Párrafo de responsabilidad de la administración del contribuyente.',
    },
    {
      sectionKey: 'S5', label: 'Responsabilidad de la Firma Auditora',
      description: 'Examen conforme a la NACOT; incluye declaración de independencia según el CIEPC.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: true, sourceRef: 'APF-08::S5', sortOrder: 5,
      aiHint: 'Párrafo de responsabilidad de la firma; incorpora la declaración de independencia (de APF-08).',
    },
    {
      sectionKey: 'S6', label: 'Criterios',
      description: 'Código Tributario, LISR, Ley IVA y demás disposiciones tributarias vigentes.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 6,
      aiHint: 'Marco legal usado como criterio del examen.',
    },
    {
      sectionKey: 'S7', label: 'Párrafo de Opinión (3 tipos NACOT)',
      description: 'Opinión de cumplimiento / con salvedad / de incumplimiento — según la NACOT (NO existe abstención).',
      fieldType: FieldType.ENUM_SELECT, isRequired: true, isAutoFilled: false, sortOrder: 7,
      options: ['Opinión de cumplimiento', 'Opinión con salvedad', 'Opinión de incumplimiento'],
      aiHint: 'El tipo de opinión lo sugiere el semáforo de la Cédula de Diferencias (D-03). Si es con salvedad, pre-redacta el incumplimiento con referencia legal.',
    },
    {
      sectionKey: 'S8', label: 'Firma',
      description: 'Nombre del socio/auditor, número de carné CVPCPA, firma, sello, ciudad y fecha.',
      fieldType: FieldType.TEXTAREA, isRequired: true, isAutoFilled: false, sortOrder: 8,
      aiHint: 'Bloque de firma con carné CVPCPA vigente del auditor firmante.',
    },
    {
      sectionKey: 'S9', label: 'Nota — Referencia al Anexo 12',
      description: 'Si hay incumplimientos formales o sustantivos, referencia al Anexo 12 del Informe Fiscal.',
      fieldType: FieldType.TEXTAREA, isRequired: false, isAutoFilled: false, sortOrder: 9,
      aiHint: 'Incluye la nota de referencia al Anexo 12 cuando existan incumplimientos.',
    },
  ],
};
