export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CAE = 'CAE',
  AUDIT_MANAGER = 'AUDIT_MANAGER',
  SENIOR_AUDITOR = 'SENIOR_AUDITOR',
  AUDITOR = 'AUDITOR',
  AUDITEE = 'AUDITEE',
  READ_ONLY = 'READ_ONLY',
}

export const ROLE_LEVEL: Record<UserRole, number> = {
  [UserRole.SUPER_ADMIN]: 100,
  [UserRole.ADMIN]: 90,
  [UserRole.CAE]: 80,
  [UserRole.AUDIT_MANAGER]: 70,
  [UserRole.SENIOR_AUDITOR]: 60,
  [UserRole.AUDITOR]: 50,
  [UserRole.AUDITEE]: 20,
  [UserRole.READ_ONLY]: 10,
};

export enum AuditType {
  FINANCIAL = 'FINANCIAL',
  OPERATIONAL = 'OPERATIONAL',
  COMPLIANCE = 'COMPLIANCE',
  IT = 'IT',
  FORENSIC = 'FORENSIC',
  INTEGRATED = 'INTEGRATED',
  FOLLOW_UP = 'FOLLOW_UP',
  SPECIAL = 'SPECIAL',
  ESG = 'ESG',
}

export enum AuditStatus {
  DRAFT = 'DRAFT',
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  FIELDWORK = 'FIELDWORK',
  REVIEW = 'REVIEW',
  REPORTING = 'REPORTING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
}

export enum RiskLevel {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  MINIMAL = 'MINIMAL',
}

export enum FindingSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFORMATIONAL = 'INFORMATIONAL',
}

export enum FindingStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  COMMUNICATED = 'COMMUNICATED',
  IN_REMEDIATION = 'IN_REMEDIATION',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  DISPUTED = 'DISPUTED',
  ACCEPTED_RISK = 'ACCEPTED_RISK',
}

export enum WorkingPaperType {
  PLANNING = 'PLANNING',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  CONTROL_TESTING = 'CONTROL_TESTING',
  SUBSTANTIVE = 'SUBSTANTIVE',
  ANALYTICAL = 'ANALYTICAL',
  FINDING = 'FINDING',
  SUMMARY = 'SUMMARY',
  PERMANENT = 'PERMANENT',
  DATA_ANALYSIS = 'DATA_ANALYSIS',
}

export enum WorkingPaperStatus {
  DRAFT = 'DRAFT',
  IN_REVIEW = 'IN_REVIEW',
  REVIEWED = 'REVIEWED',
  APPROVED = 'APPROVED',
  FINAL = 'FINAL',
}

export enum TickMark {
  VERIFIED = 'VERIFIED',
  EXCEPTION = 'EXCEPTION',
  ESTIMATED = 'ESTIMATED',
  CONFIRMED_THIRD = 'CONFIRMED_THIRD',
  RECALCULATED = 'RECALCULATED',
  FOOTED = 'FOOTED',
  CROSS_FOOTED = 'CROSS_FOOTED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  PENDING = 'PENDING',
  ATTENTION = 'ATTENTION',
}

export enum WorkingPaperIndex {
  A = 'A',   // Planning
  B = 'B',   // Controls
  C = 'C',   // Substantive
  D = 'D',   // Findings
  E = 'E',   // Closure
  AD = 'AD', // Data Analysis
}

export enum ConfirmationType {
  BANK = 'BANK',
  CLIENT = 'CLIENT',
  LAWYER = 'LAWYER',
  SUPPLIER = 'SUPPLIER',
}

export enum ConfirmationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  RECEIVED = 'RECEIVED',
  CONFIRMED = 'CONFIRMED',
  DISPUTED = 'DISPUTED',
  NO_RESPONSE = 'NO_RESPONSE',
  SECOND_REQUEST = 'SECOND_REQUEST',
}

export enum PbcRequestStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  OVERDUE = 'OVERDUE',
}

export enum RagBase {
  IIA_2025 = 'IIA_2025',
  AUDIT_TI = 'AUDIT_TI',
  CONTINUITY = 'CONTINUITY',
  COMPLIANCE = 'COMPLIANCE',
  ANTI_FRAUD = 'ANTI_FRAUD',
  AI_GOVERNANCE = 'AI_GOVERNANCE',
  CLIENT_NORMATIVE = 'CLIENT_NORMATIVE',
  FINANCIAL = 'FINANCIAL',
  SECTOR_SPECIFIC = 'SECTOR_SPECIFIC',
}

export enum AiAgentType {
  MINERVA = 'MINERVA',
  SCRIPTORIUM = 'SCRIPTORIUM',
  ARGUS = 'ARGUS',
  HERMES = 'HERMES',
  CICERO = 'CICERO',
  SOCRATES = 'SOCRATES',
  CASSANDRA = 'CASSANDRA',
  VULCANO = 'VULCANO',
  SENADO = 'SENADO',
  ATLAS = 'ATLAS',
  FENIX = 'FENIX',
  FISCUS = 'FISCUS',
  SHERLOCK = 'SHERLOCK',
  MINERVA_QAIP = 'MINERVA_QAIP',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SLACK = 'SLACK',
  TEAMS = 'TEAMS',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  TRIAL = 'TRIAL',
}

export enum RecommendationStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  IMPLEMENTED = 'IMPLEMENTED',
  VERIFIED = 'VERIFIED',
  CLOSED = 'CLOSED',
  OVERDUE = 'OVERDUE',
}

export enum EvidenceType {
  DOCUMENT = 'DOCUMENT',
  SPREADSHEET = 'SPREADSHEET',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DATABASE_EXPORT = 'DATABASE_EXPORT',
  SYSTEM_LOG = 'SYSTEM_LOG',
  INTERVIEW_NOTES = 'INTERVIEW_NOTES',
  OBSERVATION = 'OBSERVATION',
  EXTERNAL_CONFIRMATION = 'EXTERNAL_CONFIRMATION',
  THIRD_PARTY_REPORT = 'THIRD_PARTY_REPORT',
}

export enum ControlType {
  PREVENTIVE = 'PREVENTIVE',
  DETECTIVE = 'DETECTIVE',
  CORRECTIVE = 'CORRECTIVE',
  COMPENSATING = 'COMPENSATING',
}

export enum ControlNature {
  MANUAL = 'MANUAL',
  AUTOMATED = 'AUTOMATED',
  SEMI_AUTOMATED = 'SEMI_AUTOMATED',
}

export enum TestingApproach {
  INQUIRY = 'INQUIRY',
  OBSERVATION = 'OBSERVATION',
  INSPECTION = 'INSPECTION',
  RECALCULATION = 'RECALCULATION',
  REPERFORMANCE = 'REPERFORMANCE',
  ANALYTICAL = 'ANALYTICAL',
  CONFIRMATION = 'CONFIRMATION',
}
